# Generated by Django 4.2 on 2023-05-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.EmailField(max_length=30)),
                ('invoice_no', models.IntegerField(unique=True)),
                ('total_bill', models.IntegerField()),
                ('payment', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Checkout',
            },
        ),
    ]
